# Generated by Django 5.0.4 on 2024-04-22 13:32

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=(django.db.models.functions.text.Lower('doctor'), 'work_day', 'start_time', 'end_time'), name='unique_availability', violation_error_message='A doctor must be available at any unique time and day'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='check_availability_time', violation_error_message='Start time of availability must be less than its end time'),
        ),
    ]
