# Generated by Django 5.0.4 on 2024-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_available_availability_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_availability',
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('doctor', 'work_day', 'start_time', 'end_time'), name='unique_availability', violation_error_message='A doctor must be available at any unique time and day'),
        ),
    ]
