# Generated by Django 5.0.4 on 2024-04-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctor_workplace_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='workplace',
            field=models.ForeignKey(default='data unavailable', on_delete=django.db.models.deletion.RESTRICT, to='accounts.institution'),
            preserve_default=False,
        ),
    ]
