# Generated by Django 5.0.4 on 2024-05-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visited_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'pending'), ('v', 'visited'), ('m', 'missed')], default='p', max_length=1)),
                ('doctor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.availability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Disposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('prescription', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.appointment')),
            ],
        ),
    ]
