# Generated by Django 5.0.4 on 2024-05-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposals',
            old_name='disease',
            new_name='problem',
        ),
    ]
