# Generated by Django 5.0.4 on 2024-04-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_availability_unique_availability_and_more'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='accounts.availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='visited_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
