# Generated by Django 5.0.4 on 2024-04-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_availability_unique_availability_and_more'),
        ('index', '0002_remove_appointment_doctor_remove_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_schedule',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='visited_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
