# Generated by Django 5.0.4 on 2024-04-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_availability_unique_availability_and_more'),
        ('index', '0003_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='visited_time',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
