# Generated by Django 5.0.4 on 2024-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_appointment_doctor_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visited_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
