# Generated by Django 5.0.4 on 2024-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_prescription_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='symptoms',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
