# Generated by Django 5.0.4 on 2024-04-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_appointment_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visited',
        ),
    ]
