# Generated by Django 5.0.4 on 2024-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_appointment_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visited',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('v', 'visited'), ('c', 'canceled'), ('m', 'missed')], default='p', max_length=1),
        ),
    ]
