# Generated by Django 5.0.4 on 2024-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_appointment_visited_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('v', 'visited'), ('m', 'missed')], default='p', max_length=1),
        ),
    ]
